"""empty message

Revision ID: 01d296963b37
Revises: 359f51fc78de
Create Date: 2025-08-14 16:11:26.460697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d296963b37'
down_revision = '359f51fc78de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_telefonico', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_column('numero_telefonico')

    # ### end Alembic commands ###
