"""empty message

Revision ID: 059b99054dda
Revises: 19a1fce17583
Create Date: 2025-10-10 13:32:45.750040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059b99054dda'
down_revision = '19a1fce17583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('segundo_nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segundo_nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
