"""empty message

Revision ID: 05a3163c6b4c
Revises: 590cb578fcc4
Create Date: 2025-10-10 12:06:02.634628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a3163c6b4c'
down_revision = '590cb578fcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('colonia', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primer_nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('segundo_nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('curp', sa.String(length=18), nullable=False))
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('proveedor_verificacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['rfc'])
        batch_op.create_unique_constraint(None, ['curp'])
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fecha_verificacion')
        batch_op.drop_column('proveedor_verificacion')
        batch_op.drop_column('verificado')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('nacionalidad')
        batch_op.drop_column('rfc')
        batch_op.drop_column('curp')
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')
        batch_op.drop_column('segundo_nombre')
        batch_op.drop_column('primer_nombre')

    op.drop_table('domicilio')
    # ### end Alembic commands ###
