"""empty message

Revision ID: 077ba0f8f7dd
Revises: e7d17459afa8
Create Date: 2025-08-04 18:51:03.111176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077ba0f8f7dd'
down_revision = 'e7d17459afa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('almacenamiento', sa.String(length=120), nullable=False),
    sa.Column('anio', sa.String(length=120), nullable=False),
    sa.Column('ram', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogo_modelos')
    # ### end Alembic commands ###
