"""empty message

Revision ID: 0805dd101430
Revises: 2249651e74c2
Create Date: 2025-10-23 14:48:55.191721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0805dd101430'
down_revision = '2249651e74c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pago_inicial', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pago_semanal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('num_pagos_semanales', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_column('num_pagos_semanales')
        batch_op.drop_column('pago_semanal')
        batch_op.drop_column('pago_inicial')
        batch_op.drop_column('precio_total')

    # ### end Alembic commands ###
