"""empty message

Revision ID: 09ab989b92e9
Revises: 8407ecfd6181
Create Date: 2025-08-07 23:44:49.494587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ab989b92e9'
down_revision = '8407ecfd6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('dual_sim', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('red_movil', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('version_android', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('procesador', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('velocidad_procesador', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cantidad_nucleos', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tamanio_pantalla', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tipo_resolucion', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('frecuencia_actualizacion_pantalla', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('resolucion_camara_trasera_principal', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('resolucion_camara_frontal_principal', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('capacidad_bateria', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('carga_rapida', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('huella_dactilar', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('resistencia_salpicaduras', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('resistencia_agua', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('resistencia_polvo', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('resistencia_caidas', sa.Boolean(), server_default=sa.text('false'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.drop_column('resistencia_caidas')
        batch_op.drop_column('resistencia_polvo')
        batch_op.drop_column('resistencia_agua')
        batch_op.drop_column('resistencia_salpicaduras')
        batch_op.drop_column('huella_dactilar')
        batch_op.drop_column('carga_rapida')
        batch_op.drop_column('capacidad_bateria')
        batch_op.drop_column('resolucion_camara_frontal_principal')
        batch_op.drop_column('resolucion_camara_trasera_principal')
        batch_op.drop_column('frecuencia_actualizacion_pantalla')
        batch_op.drop_column('tipo_resolucion')
        batch_op.drop_column('tamanio_pantalla')
        batch_op.drop_column('cantidad_nucleos')
        batch_op.drop_column('velocidad_procesador')
        batch_op.drop_column('procesador')
        batch_op.drop_column('version_android')
        batch_op.drop_column('red_movil')
        batch_op.drop_column('dual_sim')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
