"""empty message

Revision ID: 159b7b1af849
Revises: 28d15ffb50b0
Create Date: 2025-10-28 11:34:13.254401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159b7b1af849'
down_revision = '28d15ffb50b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_pago_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plan_pago', ['plan_pago_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plan_pago_id')

    # ### end Alembic commands ###
