"""empty message

Revision ID: 19a1fce17583
Revises: 05a3163c6b4c
Create Date: 2025-10-10 13:01:31.898041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a1fce17583'
down_revision = '05a3163c6b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('curp',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('nacionalidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo_identificacion',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('numero_identificacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('numero_identificacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('tipo_identificacion',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('nacionalidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('curp',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)

    # ### end Alembic commands ###
