"""empty message

Revision ID: 2249651e74c2
Revises: bf9a887bca10
Create Date: 2025-10-23 14:20:30.217137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2249651e74c2'
down_revision = 'bf9a887bca10'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dispositivo_contrato_id_fkey'), type_='foreignkey')

    op.drop_table('contrato')  # Ahora no falla porque la FK ya fue eliminada

    op.create_table('contrato_compra_venta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('detalles', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contrato_compra_venta', ['contrato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dispositivo_contrato_id_fkey'), 'contrato', ['contrato_id'], ['id'])

    op.create_table('contrato',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('detalles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('contrato_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contrato_pkey'))
    )
    op.drop_table('contrato_compra_venta')
    # ### end Alembic commands ###
