"""empty message

Revision ID: 2717c0503fd1
Revises: eb5006d2c187
Create Date: 2025-10-16 09:34:28.308502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2717c0503fd1'
down_revision = 'eb5006d2c187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
