"""empty message

Revision ID: 28d15ffb50b0
Revises: 0805dd101430
Create Date: 2025-10-28 11:04:42.591740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d15ffb50b0'
down_revision = '0805dd101430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_semanas', sa.Integer(), nullable=False),
    sa.Column('tasa_interes', sa.Float(), nullable=False),
    sa.Column('pago_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_pago')
    # ### end Alembic commands ###
