"""empty message

Revision ID: 29fe7e393cd4
Revises: 5378b5b9d53d
Create Date: 2025-10-29 11:50:05.135902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fe7e393cd4'
down_revision = '5378b5b9d53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_url', sa.String(length=550), nullable=True))
        batch_op.add_column(sa.Column('hash_contrato', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contrato_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estado_contrato', sa.Enum('PENDIENTE', 'FIRMADO', 'CANCELADO', name='estado_contrato_enum', native_enum=False), server_default=sa.text("'PENDIENTE'"), nullable=False))
        batch_op.add_column(sa.Column('fecha_firma', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_column('fecha_firma')
        batch_op.drop_column('estado_contrato')
        batch_op.drop_column('contrato_html')
        batch_op.drop_column('hash_contrato')
        batch_op.drop_column('contrato_url')

    # ### end Alembic commands ###
