"""empty message

Revision ID: 2eb8dea2ae77
Revises: 79a771087788
Create Date: 2025-11-27 11:20:23.903571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eb8dea2ae77'
down_revision = '79a771087788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('back_image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('encrypted_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('back_image')
        batch_op.drop_column('front_image')

    # ### end Alembic commands ###
