"""empty message

Revision ID: 2fea024f9a49
Revises: b668ba5b50a5
Create Date: 2025-09-09 13:17:16.376204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fea024f9a49'
down_revision = 'b668ba5b50a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
