"""empty message

Revision ID: 33a68ab1901e
Revises: b692f70990ea
Create Date: 2025-11-11 12:25:07.781573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a68ab1901e'
down_revision = 'b692f70990ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
