"""empty message

Revision ID: 3458aa715262
Revises: 1aeb40bbe4cf
Create Date: 2025-07-28 19:51:47.337704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3458aa715262'
down_revision = '1aeb40bbe4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.Enum('SOPORTE', 'ADMIN', 'VENDEDOR', name='roles_empleado', native_enum=False), server_default=sa.text("'VENDEDOR'"), nullable=False))
        batch_op.alter_column('fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
