"""empty message

Revision ID: 359f51fc78de
Revises: 09ab989b92e9
Create Date: 2025-08-11 16:57:03.538021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359f51fc78de'
down_revision = '09ab989b92e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
