"""empty message

Revision ID: 39b3c80dd00f
Revises: 3458aa715262
Create Date: 2025-07-30 16:37:39.107822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39b3c80dd00f'
down_revision = '3458aa715262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###
