"""empty message

Revision ID: 3a32a0b83c2d
Revises: bdd3c12126e1
Create Date: 2025-10-17 11:27:28.753704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a32a0b83c2d'
down_revision = 'bdd3c12126e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
