"""empty message

Revision ID: 4ca70b1c2efa
Revises: 9be34aa78a46
Create Date: 2025-11-04 14:17:17.014123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca70b1c2efa'
down_revision = '9be34aa78a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_pago_semanal', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_column('ultimo_pago_semanal')

    # ### end Alembic commands ###
