"""empty message

Revision ID: 4d50710e2eb7
Revises: dbe6569de2e5
Create Date: 2025-12-11 11:16:08.933629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50710e2eb7'
down_revision = 'dbe6569de2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursal', ['Sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Sucursal_id')

    # ### end Alembic commands ###
