"""empty message

Revision ID: 4efca343d0b7
Revises: d11f24251f70
Create Date: 2025-11-17 11:41:18.598867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4efca343d0b7'
down_revision = 'd11f24251f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))
        batch_op.alter_column('contrato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('fecha_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metodo_pago', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('contrato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('fecha')
        batch_op.drop_column('metodo')

    # ### end Alembic commands ###
