"""empty message

Revision ID: 50207eb761e3
Revises: 4d50710e2eb7
Create Date: 2025-12-11 12:34:51.480463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50207eb761e3'
down_revision = '4d50710e2eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('pago_Sucursal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sucursal', ['sucursal_id'], ['id'])
        batch_op.drop_column('Sucursal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sucursal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pago_Sucursal_id_fkey'), 'sucursal', ['Sucursal_id'], ['id'])
        batch_op.drop_column('sucursal_id')

    # ### end Alembic commands ###
