"""Modelo de sucursal y de empleado actualizados

Revision ID: 51c2375b82ef
Revises: 5ac3a84ed671
Create Date: 2025-07-17 22:09:07.542038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51c2375b82ef'
down_revision = '5ac3a84ed671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado_sucursal', sa.Enum('ACTIVA', 'CERRADA', 'SUSPENDIDA', name='estado_sucursal_enum', native_enum=False), server_default=sa.text("'ACTIVA'"), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('numero_telefonico', sa.String(length=12), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_clausura', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sucursal_nombre'), ['nombre'], unique=False)

    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado_usuario', sa.Enum('ACTIVO', 'INACTIVO', name='estado_usuario_enum', native_enum=False), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleado_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('ix_empleado_sucursal_id'), ['sucursal_id'], unique=False)

    op.drop_table('empleado_sucursal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado_sucursal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('estado_usuario', postgresql.ENUM('ACTIVO', 'INACTIVO', name='estado_usuario_enum'), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empleado_sucursal_pkey'))
    )
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleado_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_empleado_correo'))

    op.drop_table('empleado')
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursal_nombre'))

    op.drop_table('sucursal')
    # ### end Alembic commands ###
