"""empty message

Revision ID: 5378b5b9d53d
Revises: 8829c732f695
Create Date: 2025-10-29 11:40:23.876793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5378b5b9d53d'
down_revision = '8829c732f695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_foreign_key(None, 'empleado', ['empleado_id'], ['id'])

    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('plan_pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('empleado_id')

    # ### end Alembic commands ###
