"""empty message

Revision ID: 580ab6130707
Revises: 8a68ea79774d
Create Date: 2025-12-10 18:05:26.401473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580ab6130707'
down_revision = '8a68ea79774d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.DateTime(), nullable=False),
    sa.Column('total_efectivo', sa.Float(), nullable=False),
    sa.Column('total_tarjeta', sa.Float(), nullable=False),
    sa.Column('total_transferencia', sa.Float(), nullable=False),
    sa.Column('cantidad_efectivo', sa.Integer(), nullable=False),
    sa.Column('cantidad_tarjeta', sa.Integer(), nullable=False),
    sa.Column('cantidad_transferencia', sa.Integer(), nullable=False),
    sa.Column('total_general', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.alter_column('modelo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.alter_column('modelo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('cortes_caja')
    # ### end Alembic commands ###
