"""empty message

Revision ID: 590cb578fcc4
Revises: 43d95963b0d8
Create Date: 2025-10-02 13:11:16.820102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590cb578fcc4'
down_revision = '43d95963b0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_consulta_buro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_firma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('contrato_url', sa.String(length=550), nullable=False),
    sa.Column('hash_contrato', sa.String(length=255), nullable=False),
    sa.Column('estado_contrato', sa.Enum('PENDIENTE', 'FIRMADO', 'CANCELADO', name='estado_contrato_enum', native_enum=False), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrato_consulta_buro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contrato_consulta_buro_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contrato_consulta_buro_empleado_id'), ['empleado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_consulta_buro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contrato_consulta_buro_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_contrato_consulta_buro_cliente_id'))

    op.drop_table('contrato_consulta_buro')
    # ### end Alembic commands ###
