"""empty message

Revision ID: 5ac3a84ed671
Revises: 53da6b12b55f
Create Date: 2025-07-17 19:41:05.106132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ac3a84ed671'
down_revision = '53da6b12b55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado_usuario', sa.Enum('ACTIVO', 'INACTIVO', name='estado_usuario_enum'), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empleado_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('estado_usuario', postgresql.ENUM('ACTIVO', 'INACTIVO', name='estadousuario'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empleado_usuario_pkey'))
    )
    op.drop_table('empleado_sucursal')
    # ### end Alembic commands ###
