"""empty message

Revision ID: 5e92eb52e39d
Revises: 4efca343d0b7
Create Date: 2025-11-21 11:35:48.344704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e92eb52e39d'
down_revision = '4efca343d0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')

    # ### end Alembic commands ###
