"""empty message

Revision ID: 6527078f67d6
Revises: d99046316cfe
Create Date: 2025-12-12 17:17:06.866541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6527078f67d6'
down_revision = 'd99046316cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmado_empleado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmado_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_confirmacion_empleado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cerrado_por_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleado', ['cerrado_por_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cerrado_por_admin_id')
        batch_op.drop_column('fecha_cierre')
        batch_op.drop_column('fecha_confirmacion_empleado')
        batch_op.drop_column('confirmado_admin')
        batch_op.drop_column('confirmado_empleado')

    # ### end Alembic commands ###
