"""empty message

Revision ID: 6df6fa804687
Revises: 91f716c32258
Create Date: 2025-10-14 11:21:40.371318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df6fa804687'
down_revision = '91f716c32258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_consulta_buro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_html', sa.Text(), nullable=True))
        batch_op.alter_column('hash_contrato',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_consulta_buro', schema=None) as batch_op:
        batch_op.alter_column('hash_contrato',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('contrato_html')

    # ### end Alembic commands ###
