"""empty message

Revision ID: 7d5b3a99d9a5
Revises: edb43d092d2a
Create Date: 2025-11-25 13:27:20.673384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5b3a99d9a5'
down_revision = 'edb43d092d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empleado', ['empleado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    # ### end Alembic commands ###
