"""empty message

Revision ID: 819dfe461969
Revises: 159b7b1af849
Create Date: 2025-10-28 13:09:16.645858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819dfe461969'
down_revision = '159b7b1af849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.alter_column('plan_pago_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('plan_pago', schema=None) as batch_op:
        batch_op.alter_column('tasa_interes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_pago', schema=None) as batch_op:
        batch_op.alter_column('tasa_interes',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.alter_column('plan_pago_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
