"""empty message

Revision ID: 8407ecfd6181
Revises: 077ba0f8f7dd
Create Date: 2025-08-06 21:18:38.437153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8407ecfd6181'
down_revision = '077ba0f8f7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=550), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_modelos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
