"""empty message

Revision ID: 8829c732f695
Revises: 819dfe461969
Create Date: 2025-10-28 14:37:48.117388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8829c732f695'
down_revision = '819dfe461969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_pago_fecha', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_column('proximo_pago_fecha')

    # ### end Alembic commands ###
