"""empty message

Revision ID: 8a68ea79774d
Revises: c2538aeb6ea8
Create Date: 2025-12-04 14:33:06.142031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a68ea79774d'
down_revision = 'c2538aeb6ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'catalogo_modelos', ['modelo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('modelo_id')

    # ### end Alembic commands ###
