"""empty message

Revision ID: 91f716c32258
Revises: 059b99054dda
Create Date: 2025-10-10 15:21:16.830761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f716c32258'
down_revision = '059b99054dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primer_nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=120), nullable=False))
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('apellido_paterno')
        batch_op.drop_column('primer_nombre')

    # ### end Alembic commands ###
