"""empty message

Revision ID: 9be34aa78a46
Revises: 29fe7e393cd4
Create Date: 2025-10-29 11:57:19.566328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be34aa78a46'
down_revision = '29fe7e393cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('contrato_compra_venta_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['cliente_id'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato_compra_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contrato_compra_venta_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
