"""empty message

Revision ID: a605b2c313fe
Revises: f2276a4ade83
Create Date: 2025-09-09 11:55:57.846498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a605b2c313fe'
down_revision = 'f2276a4ade83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas_verificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_consulta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=255), nullable=True),
    sa.Column('resultado_consulta', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_verificacion_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_verificacion_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_verificacion_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_consultas_verificacion_empleado_id'))

    op.drop_table('consultas_verificacion')
    # ### end Alembic commands ###
