"""empty message

Revision ID: a9e359d0e297
Revises: 50207eb761e3
Create Date: 2025-12-11 18:04:15.154364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9e359d0e297'
down_revision = '50207eb761e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corte_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('total_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tarjeta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_transferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_general', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('real_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('real_tarjeta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('real_transferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dif_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dif_tarjeta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dif_transferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('COMPLETO', 'FALTANTE', 'SOBRANTE', 'PENDIENTE', name='estadocorte'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cortes_caja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes_caja',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_corte', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_efectivo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_tarjeta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_transferencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cantidad_efectivo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_tarjeta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_transferencia', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_general', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sucursal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('empleado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], name=op.f('cortes_caja_empleado_id_fkey')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('cortes_caja_sucursal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cortes_caja_pkey'))
    )
    op.drop_table('corte_caja')
    # ### end Alembic commands ###
