"""empty message

Revision ID: b668ba5b50a5
Revises: a605b2c313fe
Create Date: 2025-09-09 13:09:00.239248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b668ba5b50a5'
down_revision = 'a605b2c313fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_verificacion', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
