"""empty message

Revision ID: bdd3c12126e1
Revises: 2717c0503fd1
Create Date: 2025-10-16 14:14:40.301009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd3c12126e1'
down_revision = '2717c0503fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_crediticio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credito_aprobado', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('credito_aprobado')
        batch_op.drop_column('score_crediticio')

    # ### end Alembic commands ###
