"""empty message

Revision ID: c2538aeb6ea8
Revises: 1d5fa211d26e
Create Date: 2025-12-02 11:47:35.560338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2538aeb6ea8'
down_revision = '1d5fa211d26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_identity_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('encrypted_front', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_back', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.drop_table('pending_identity_document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_identity_document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('encrypted_front', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('encrypted_back', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_identity_document_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('pending_identity_document_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('pending_identity_documents')
    # ### end Alembic commands ###
