"""empty message

Revision ID: d11f24251f70
Revises: 33a68ab1901e
Create Date: 2025-11-14 10:34:54.459626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11f24251f70'
down_revision = '33a68ab1901e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato_compra_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    # ### end Alembic commands ###
