"""empty message

Revision ID: d99046316cfe
Revises: a9e359d0e297
Create Date: 2025-12-11 18:11:32.849248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99046316cfe'
down_revision = 'a9e359d0e297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trans_efectivo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trans_tarjeta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trans_transferencia', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        batch_op.drop_column('trans_transferencia')
        batch_op.drop_column('trans_tarjeta')
        batch_op.drop_column('trans_efectivo')

    # ### end Alembic commands ###
