"""empty message

Revision ID: dbe6569de2e5
Revises: 580ab6130707
Create Date: 2025-12-11 09:47:53.027350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe6569de2e5'
down_revision = '580ab6130707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('cortes_caja_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empleado', ['empleado_id'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cortes_caja_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('empleado_id')

    # ### end Alembic commands ###
