"""empty message

Revision ID: e7d17459afa8
Revises: 39b3c80dd00f
Create Date: 2025-07-30 20:43:59.383104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d17459afa8'
down_revision = '39b3c80dd00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_pendiente', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('correo_token_antiguo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('correo_token_nuevo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('correo_antiguo_confirmado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('correo_nuevo_confirmado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('correo_token_expira', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_empleado_correo_pendiente'), ['correo_pendiente'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleado_correo_pendiente'))
        batch_op.drop_column('correo_token_expira')
        batch_op.drop_column('correo_nuevo_confirmado')
        batch_op.drop_column('correo_antiguo_confirmado')
        batch_op.drop_column('correo_token_nuevo')
        batch_op.drop_column('correo_token_antiguo')
        batch_op.drop_column('correo_pendiente')

    # ### end Alembic commands ###
