"""empty message

Revision ID: f2276a4ade83
Revises: 01d296963b37
Create Date: 2025-08-28 12:58:47.361179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2276a4ade83'
down_revision = '01d296963b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('numero_telefonico_adicional', sa.String(length=12), nullable=True),
    sa.Column('numero_telefonico', sa.String(length=12), nullable=True),
    sa.Column('tipo_identificacion', sa.Enum('passport', 'id_card', 'driver_license', 'residence_permit', 'identity_card', name='tipo_identificacion_enum', native_enum=False), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_usuario', sa.Enum('ACTIVO', 'INACTIVO', 'MOROSO', 'BLOQUEADO', 'ELIMINADO', name='estado_usuario_enum', native_enum=False), nullable=False),
    sa.Column('notas', sa.String(length=1500), nullable=True),
    sa.Column('datos_biometricos', sa.String(length=1500), nullable=True),
    sa.Column('fotografia_url', sa.String(length=550), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_identificacion')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_correo'), ['correo'], unique=True)

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('estado_usuario',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ACTIVO', 'INACTIVO', 'MOROSO', 'BLOQUEADO', 'ELIMINADO', name='estado_usuario_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVO'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('estado_usuario',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', 'MOROSO', 'BLOQUEADO', 'ELIMINADO', name='estado_usuario_enum', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVO'::character varying"))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_correo'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
